# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.luks.devices."luksdev".device = "/dev/disk/by-uuid/d323a2e4-89be-4ded-aca1-b47b98280090";
  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1B64-E2BB";
      fsType = "vfat";
    };

  fileSystems."/" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@nixos" "compress=zstd" "noatime" ];
    };


  fileSystems."/persist" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@persist" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/files" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@files" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@nixos-log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/var/lib/flatpak" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@flatpak" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/lib/libvirt" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@libvirt" "compress=zstd" "noatime" ];
    };

  fileSystems."/swap" =
    { device = "/dev/mapper/luksdev";
      fsType = "btrfs";
      options = [ "subvol=@swap" "compress=zstd" "noatime" ];
    };


  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
